export const mockSuppliers = [
  {
    id: 1,
    name: "Công ty Thực phẩm Sạch ABC",
    supplierCode: "SUP-001",
    taxCode: "0102030405",
    contactPerson: "Nguyễn Văn An",
    phone: "0901234567",
    email: "an.nv@abcfood.vn",
    address: "Số 12 Bến Vân Đồn, Quận 4, TP.HCM",
    type: "FOOD",
    status: "ACTIVE",
    contractStatusCached: "ACTIVE",
    contractStartAtCached: "2026-01-01",
    contractEndAtCached: "2026-12-31",
    ratingAvgCached: 4.8,
    ratingCountCached: 18,
    dishCount: 24,
    orderCount: 1420,
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=ABC"
  },
  {
    id: 2,
    name: "Hợp tác xã Nông nghiệp Xanh",
    supplierCode: "SUP-002",
    taxCode: "0314159265",
    contactPerson: "Trần Thị Bích",
    phone: "0912233445",
    email: "bich.tt@xanhfarm.vn",
    address: "Ấp 3, Xã Tân Thạnh Đông, Củ Chi, TP.HCM",
    type: "FRESH_FOOD",
    status: "ACTIVE",
    contractStatusCached: "ACTIVE",
    contractStartAtCached: "2026-01-15",
    contractEndAtCached: "2026-10-15",
    ratingAvgCached: 4.5,
    ratingCountCached: 12,
    dishCount: 16,
    orderCount: 980,
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=HTX"
  },
  {
    id: 3,
    name: "Dịch vụ Suất ăn Công nghiệp H&H",
    supplierCode: "SUP-003",
    taxCode: "0892738192",
    contactPerson: "Lê Hoàng Hùng",
    phone: "0987654321",
    email: "hung.lh@hhcatering.com",
    address: "Khu công nghiệp Cát Lái, TP. Thủ Đức, TP.HCM",
    type: "FOOD",
    status: "EXPIRING_SOON",
    contractStatusCached: "EXPIRING_SOON",
    contractStartAtCached: "2025-04-10",
    contractEndAtCached: "2026-04-10",
    ratingAvgCached: 3.8,
    ratingCountCached: 8,
    dishCount: 30,
    orderCount: 2150,
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=HH"
  },
  {
    id: 4,
    name: "Công ty CP Chế biến Hải sản Vũng Tàu",
    supplierCode: "SUP-004",
    taxCode: "0778899001",
    contactPerson: "Phạm Minh Thuận",
    phone: "0933445566",
    email: "thuan.pm@seafoodvt.vn",
    address: "Cảng Cá Cát Lở, Phường 11, TP. Vũng Tàu",
    type: "MEAT_SEAFOOD",
    status: "ACTIVE",
    contractStatusCached: "ACTIVE",
    contractStartAtCached: "2026-02-01",
    contractEndAtCached: "2027-01-20",
    ratingAvgCached: 5.0,
    ratingCountCached: 25,
    dishCount: 18,
    orderCount: 1680,
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=VST"
  },
  {
    id: 5,
    name: "Cánh Đồng Vàng Food",
    supplierCode: "SUP-005",
    taxCode: "0112233445",
    contactPerson: "Hoàng Kim Chi",
    phone: "0944556677",
    email: "chi.hk@canhdongvang.com",
    address: "Km 18, QL 1A, Bình Chánh, TP.HCM",
    type: "DRY_FOOD",
    status: "EXPIRED",
    contractStatusCached: "EXPIRED",
    contractStartAtCached: "2025-03-01",
    contractEndAtCached: "2026-03-01",
    ratingAvgCached: 3.2,
    ratingCountCached: 6,
    dishCount: 12,
    orderCount: 650,
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=CDV"
  },
  {
    id: 6,
    name: "Gia vị Hảo Hạng Tân Bình",
    supplierCode: "SUP-006",
    taxCode: "0556677889",
    contactPerson: "Vũ Quang Hải",
    phone: "0955667788",
    email: "hai.vq@giavihaohang.vn",
    address: "Số 45 Trường Chinh, P.14, Q. Tân Bình, TP.HCM",
    type: "DRY_FOOD",
    status: "ACTIVE",
    contractStatusCached: "ACTIVE",
    contractStartAtCached: "2025-08-30",
    contractEndAtCached: "2026-08-30",
    ratingAvgCached: 4.4,
    ratingCountCached: 15,
    dishCount: 10,
    orderCount: 820,
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=GVH"
  },
];

export const mockSummary = {
  total: 6,
  active: 4,
  expiringSoon: 1,
  expired: 1,
};
